//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eChandanCanteen.CanteenProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CanteenProxy.IChandanCanteenService")]
    public interface IChandanCanteenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Insert_Modify_item_master", ReplyAction="http://tempuri.org/IChandanCanteenService/Insert_Modify_item_masterResponse")]
        string Insert_Modify_item_master(string item_id, string item_Name, int pack_qty, string pack_type, string prodCategory, string prodType, string hsn, decimal rate, decimal discount_perc, string TaxIncluded, decimal taxPerc, int ROL, string discontinue, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/GetQueryResult", ReplyAction="http://tempuri.org/IChandanCanteenService/GetQueryResultResponse")]
        System.Data.DataSet GetQueryResult(string query, string Database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/QueryExecute", ReplyAction="http://tempuri.org/IChandanCanteenService/QueryExecuteResponse")]
        string QueryExecute(string query, string Database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/feedCategory", ReplyAction="http://tempuri.org/IChandanCanteenService/feedCategoryResponse")]
        string feedCategory(string cat_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/getVendorDetail", ReplyAction="http://tempuri.org/IChandanCanteenService/getVendorDetailResponse")]
        System.Data.DataSet getVendorDetail(string vend_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/NewAndModifyVendor", ReplyAction="http://tempuri.org/IChandanCanteenService/NewAndModifyVendorResponse")]
        string NewAndModifyVendor(string vend_code, string vend_name, string address, string phone, string mobile_no, string tin_no, string state, string district, string task, string remark, string ledger_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/fillState", ReplyAction="http://tempuri.org/IChandanCanteenService/fillStateResponse")]
        System.Data.DataSet fillState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/fillDistrict", ReplyAction="http://tempuri.org/IChandanCanteenService/fillDistrictResponse")]
        System.Data.DataSet fillDistrict(string state_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/getPurchIds", ReplyAction="http://tempuri.org/IChandanCanteenService/getPurchIdsResponse")]
        System.Data.DataSet getPurchIds(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Ins_Purchase", ReplyAction="http://tempuri.org/IChandanCanteenService/Ins_PurchaseResponse")]
        string Ins_Purchase(
                    string Purch_id, 
                    string unit_id, 
                    string comp_code, 
                    string pur_type, 
                    string Vendor_Code, 
                    string Inv_No, 
                    string Inv_Date, 
                    string Item_id, 
                    string hsn, 
                    string mfd_id, 
                    string Batch_No, 
                    string Exp_Date, 
                    decimal MRP, 
                    decimal trade, 
                    string pack_type, 
                    int pack_qty, 
                    decimal Quantity, 
                    decimal It_Free, 
                    decimal DisPer, 
                    int Tax_id, 
                    decimal BestRate, 
                    string Remark, 
                    string CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/getPurchaseRecordByPurchId", ReplyAction="http://tempuri.org/IChandanCanteenService/getPurchaseRecordByPurchIdResponse")]
        System.Data.DataSet getPurchaseRecordByPurchId(string purch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Delete_Purchase", ReplyAction="http://tempuri.org/IChandanCanteenService/Delete_PurchaseResponse")]
        string Delete_Purchase(string auto_id, string purch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/PurchasePosting", ReplyAction="http://tempuri.org/IChandanCanteenService/PurchasePostingResponse")]
        string PurchasePosting(string[] p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/feedProductIssueDept", ReplyAction="http://tempuri.org/IChandanCanteenService/feedProductIssueDeptResponse")]
        string feedProductIssueDept(string dept_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/IssueToUse", ReplyAction="http://tempuri.org/IChandanCanteenService/IssueToUseResponse")]
        string IssueToUse(string unit_id, string item_id, string master_key_id, int issued_qty, string login_id, string issuedTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Retail_InsertSale", ReplyAction="http://tempuri.org/IChandanCanteenService/Retail_InsertSaleResponse")]
        string Retail_InsertSale(
                    out string processInfo, 
                    System.Data.DataSet ds, 
                    string unit_id, 
                    string card_no, 
                    string sale_type, 
                    string order_no, 
                    string payType, 
                    string payremark, 
                    string cust_name, 
                    string emp_code, 
                    string emp_name, 
                    string hospipopno, 
                    string login_id, 
                    string party_id, 
                    string old_sale_inv_no, 
                    string cancel_remark, 
                    int TokenNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Receive_Payment", ReplyAction="http://tempuri.org/IChandanCanteenService/Receive_PaymentResponse")]
        string Receive_Payment(string unit_id, string party_id, string party_name, decimal amount, string remark, string paymode, string tran_no, string login_id, string prm_1, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/DeleteIssuedItems", ReplyAction="http://tempuri.org/IChandanCanteenService/DeleteIssuedItemsResponse")]
        string DeleteIssuedItems(out string processInfo, int auto_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/ReconcileProduct2", ReplyAction="http://tempuri.org/IChandanCanteenService/ReconcileProduct2Response")]
        System.Data.DataSet ReconcileProduct2(out string processInfo, string unit_id, string logic, string prm_1, string prm_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Insert_Modify_Audit_master", ReplyAction="http://tempuri.org/IChandanCanteenService/Insert_Modify_Audit_masterResponse")]
        string Insert_Modify_Audit_master(string unit_id, string entry_type, string audit_no, string master_key_id, int qty, string login_id, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChandanCanteenService/Auto_DispatchForDamageOrExtra", ReplyAction="http://tempuri.org/IChandanCanteenService/Auto_DispatchForDamageOrExtraResponse")]
        string Auto_DispatchForDamageOrExtra(string audit_no, string login_id, string trf_from, string trf_to, string logic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChandanCanteenServiceChannel : eChandanCanteen.CanteenProxy.IChandanCanteenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChandanCanteenServiceClient : System.ServiceModel.ClientBase<eChandanCanteen.CanteenProxy.IChandanCanteenService>, eChandanCanteen.CanteenProxy.IChandanCanteenService {
        
        public ChandanCanteenServiceClient() {
        }
        
        public ChandanCanteenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChandanCanteenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChandanCanteenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChandanCanteenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert_Modify_item_master(string item_id, string item_Name, int pack_qty, string pack_type, string prodCategory, string prodType, string hsn, decimal rate, decimal discount_perc, string TaxIncluded, decimal taxPerc, int ROL, string discontinue, string Logic) {
            return base.Channel.Insert_Modify_item_master(item_id, item_Name, pack_qty, pack_type, prodCategory, prodType, hsn, rate, discount_perc, TaxIncluded, taxPerc, ROL, discontinue, Logic);
        }
        
        public System.Data.DataSet GetQueryResult(string query, string Database) {
            return base.Channel.GetQueryResult(query, Database);
        }
        
        public string QueryExecute(string query, string Database) {
            return base.Channel.QueryExecute(query, Database);
        }
        
        public string feedCategory(string cat_name) {
            return base.Channel.feedCategory(cat_name);
        }
        
        public System.Data.DataSet getVendorDetail(string vend_code) {
            return base.Channel.getVendorDetail(vend_code);
        }
        
        public string NewAndModifyVendor(string vend_code, string vend_name, string address, string phone, string mobile_no, string tin_no, string state, string district, string task, string remark, string ledger_id) {
            return base.Channel.NewAndModifyVendor(vend_code, vend_name, address, phone, mobile_no, tin_no, state, district, task, remark, ledger_id);
        }
        
        public System.Data.DataSet fillState() {
            return base.Channel.fillState();
        }
        
        public System.Data.DataSet fillDistrict(string state_code) {
            return base.Channel.fillDistrict(state_code);
        }
        
        public System.Data.DataSet getPurchIds(int num) {
            return base.Channel.getPurchIds(num);
        }
        
        public string Ins_Purchase(
                    string Purch_id, 
                    string unit_id, 
                    string comp_code, 
                    string pur_type, 
                    string Vendor_Code, 
                    string Inv_No, 
                    string Inv_Date, 
                    string Item_id, 
                    string hsn, 
                    string mfd_id, 
                    string Batch_No, 
                    string Exp_Date, 
                    decimal MRP, 
                    decimal trade, 
                    string pack_type, 
                    int pack_qty, 
                    decimal Quantity, 
                    decimal It_Free, 
                    decimal DisPer, 
                    int Tax_id, 
                    decimal BestRate, 
                    string Remark, 
                    string CreatedBy) {
            return base.Channel.Ins_Purchase(Purch_id, unit_id, comp_code, pur_type, Vendor_Code, Inv_No, Inv_Date, Item_id, hsn, mfd_id, Batch_No, Exp_Date, MRP, trade, pack_type, pack_qty, Quantity, It_Free, DisPer, Tax_id, BestRate, Remark, CreatedBy);
        }
        
        public System.Data.DataSet getPurchaseRecordByPurchId(string purch_id) {
            return base.Channel.getPurchaseRecordByPurchId(purch_id);
        }
        
        public string Delete_Purchase(string auto_id, string purch_id) {
            return base.Channel.Delete_Purchase(auto_id, purch_id);
        }
        
        public string PurchasePosting(string[] p) {
            return base.Channel.PurchasePosting(p);
        }
        
        public string feedProductIssueDept(string dept_name) {
            return base.Channel.feedProductIssueDept(dept_name);
        }
        
        public string IssueToUse(string unit_id, string item_id, string master_key_id, int issued_qty, string login_id, string issuedTo) {
            return base.Channel.IssueToUse(unit_id, item_id, master_key_id, issued_qty, login_id, issuedTo);
        }
        
        public string Retail_InsertSale(
                    out string processInfo, 
                    System.Data.DataSet ds, 
                    string unit_id, 
                    string card_no, 
                    string sale_type, 
                    string order_no, 
                    string payType, 
                    string payremark, 
                    string cust_name, 
                    string emp_code, 
                    string emp_name, 
                    string hospipopno, 
                    string login_id, 
                    string party_id, 
                    string old_sale_inv_no, 
                    string cancel_remark, 
                    int TokenNo) {
            return base.Channel.Retail_InsertSale(out processInfo, ds, unit_id, card_no, sale_type, order_no, payType, payremark, cust_name, emp_code, emp_name, hospipopno, login_id, party_id, old_sale_inv_no, cancel_remark, TokenNo);
        }
        
        public string Receive_Payment(string unit_id, string party_id, string party_name, decimal amount, string remark, string paymode, string tran_no, string login_id, string prm_1, string Logic) {
            return base.Channel.Receive_Payment(unit_id, party_id, party_name, amount, remark, paymode, tran_no, login_id, prm_1, Logic);
        }
        
        public string DeleteIssuedItems(out string processInfo, int auto_id) {
            return base.Channel.DeleteIssuedItems(out processInfo, auto_id);
        }
        
        public System.Data.DataSet ReconcileProduct2(out string processInfo, string unit_id, string logic, string prm_1, string prm_2) {
            return base.Channel.ReconcileProduct2(out processInfo, unit_id, logic, prm_1, prm_2);
        }
        
        public string Insert_Modify_Audit_master(string unit_id, string entry_type, string audit_no, string master_key_id, int qty, string login_id, string Logic) {
            return base.Channel.Insert_Modify_Audit_master(unit_id, entry_type, audit_no, master_key_id, qty, login_id, Logic);
        }
        
        public string Auto_DispatchForDamageOrExtra(string audit_no, string login_id, string trf_from, string trf_to, string logic) {
            return base.Channel.Auto_DispatchForDamageOrExtra(audit_no, login_id, trf_from, trf_to, logic);
        }
    }
}
