//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eChandanCanteen.hisProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http:www.itdoseinfo.com/2012/11/17", ConfigurationName="hisProxy.ChandanPharmacyServicesSoap")]
    public interface ChandanPharmacyServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/createUpdateItemMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string createUpdateItemMaster(string category, string itemId, string itemName, string mfdName, string genericName, string cimsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getDcotorIndentByUHID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getDcotorIndentByUHID(string UHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/closeOPDIndent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string closeOPDIndent(string IndentNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getPatientLastAppointmentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getPatientLastAppointmentDetails(string UHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/doctorMedicineItemSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string doctorMedicineItemSearch(string searchType, string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/saveIPDIssueReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveIPDIssueReturn(string billDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/LoadDoctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoadDoctor();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChandanPharmacyServicesSoapChannel : eChandanCanteen.hisProxy.ChandanPharmacyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChandanPharmacyServicesSoapClient : System.ServiceModel.ClientBase<eChandanCanteen.hisProxy.ChandanPharmacyServicesSoap>, eChandanCanteen.hisProxy.ChandanPharmacyServicesSoap {
        
        public ChandanPharmacyServicesSoapClient() {
        }
        
        public ChandanPharmacyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChandanPharmacyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChandanPharmacyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChandanPharmacyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createUpdateItemMaster(string category, string itemId, string itemName, string mfdName, string genericName, string cimsId) {
            return base.Channel.createUpdateItemMaster(category, itemId, itemName, mfdName, genericName, cimsId);
        }
        
        public string getDcotorIndentByUHID(string UHID) {
            return base.Channel.getDcotorIndentByUHID(UHID);
        }
        
        public string closeOPDIndent(string IndentNo) {
            return base.Channel.closeOPDIndent(IndentNo);
        }
        
        public string getPatientLastAppointmentDetails(string UHID) {
            return base.Channel.getPatientLastAppointmentDetails(UHID);
        }
        
        public string doctorMedicineItemSearch(string searchType, string prefix) {
            return base.Channel.doctorMedicineItemSearch(searchType, prefix);
        }
        
        public string saveIPDIssueReturn(string billDetails) {
            return base.Channel.saveIPDIssueReturn(billDetails);
        }
        
        public string LoadDoctor() {
            return base.Channel.LoadDoctor();
        }
    }
}
