//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInventory.InternalMail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternalMail.InternalMail_WebServiceSoap")]
    public interface InternalMail_WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        eInventory.InternalMail.HelloWorldResponse HelloWorld(eInventory.InternalMail.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name path from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileToWebServer", ReplyAction="*")]
        eInventory.InternalMail.UploadFileToWebServerResponse UploadFileToWebServer(eInventory.InternalMail.UploadFileToWebServerRequest request);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadFileFromWebServer", ReplyAction="*")]
        eInventory.InternalMail.DownLoadFileFromWebServerResponse DownLoadFileFromWebServer(eInventory.InternalMail.DownLoadFileFromWebServerRequest request);
        
        // CODEGEN: Generating message contract since element name loginId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewMail", ReplyAction="*")]
        eInventory.InternalMail.NewMailResponse NewMail(eInventory.InternalMail.NewMailRequest request);
        
        // CODEGEN: Generating message contract since element name loginId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContinueMail", ReplyAction="*")]
        eInventory.InternalMail.ContinueMailResponse ContinueMail(eInventory.InternalMail.ContinueMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(eInventory.InternalMail.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(eInventory.InternalMail.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToWebServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileToWebServer", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.UploadFileToWebServerRequestBody Body;
        
        public UploadFileToWebServerRequest() {
        }
        
        public UploadFileToWebServerRequest(eInventory.InternalMail.UploadFileToWebServerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileToWebServerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] data;
        
        public UploadFileToWebServerRequestBody() {
        }
        
        public UploadFileToWebServerRequestBody(string path, string filename, byte[] data) {
            this.path = path;
            this.filename = filename;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToWebServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileToWebServerResponse", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.UploadFileToWebServerResponseBody Body;
        
        public UploadFileToWebServerResponse() {
        }
        
        public UploadFileToWebServerResponse(eInventory.InternalMail.UploadFileToWebServerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileToWebServerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileToWebServerResult;
        
        public UploadFileToWebServerResponseBody() {
        }
        
        public UploadFileToWebServerResponseBody(string UploadFileToWebServerResult) {
            this.UploadFileToWebServerResult = UploadFileToWebServerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileFromWebServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFileFromWebServer", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.DownLoadFileFromWebServerRequestBody Body;
        
        public DownLoadFileFromWebServerRequest() {
        }
        
        public DownLoadFileFromWebServerRequest(eInventory.InternalMail.DownLoadFileFromWebServerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileFromWebServerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public DownLoadFileFromWebServerRequestBody() {
        }
        
        public DownLoadFileFromWebServerRequestBody(string filename, string path) {
            this.filename = filename;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileFromWebServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFileFromWebServerResponse", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.DownLoadFileFromWebServerResponseBody Body;
        
        public DownLoadFileFromWebServerResponse() {
        }
        
        public DownLoadFileFromWebServerResponse(eInventory.InternalMail.DownLoadFileFromWebServerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileFromWebServerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownLoadFileFromWebServerResult;
        
        public DownLoadFileFromWebServerResponseBody() {
        }
        
        public DownLoadFileFromWebServerResponseBody(byte[] DownLoadFileFromWebServerResult) {
            this.DownLoadFileFromWebServerResult = DownLoadFileFromWebServerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewMail", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.NewMailRequestBody Body;
        
        public NewMailRequest() {
        }
        
        public NewMailRequest(eInventory.InternalMail.NewMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TowhomSent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Conversation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strFilename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] data;
        
        public NewMailRequestBody() {
        }
        
        public NewMailRequestBody(string loginId, string TowhomSent, string Subject, string Conversation, string strFilename, byte[] data) {
            this.loginId = loginId;
            this.TowhomSent = TowhomSent;
            this.Subject = Subject;
            this.Conversation = Conversation;
            this.strFilename = strFilename;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.NewMailResponseBody Body;
        
        public NewMailResponse() {
        }
        
        public NewMailResponse(eInventory.InternalMail.NewMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NewMailResult;
        
        public NewMailResponseBody() {
        }
        
        public NewMailResponseBody(string NewMailResult) {
            this.NewMailResult = NewMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContinueMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContinueMail", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.ContinueMailRequestBody Body;
        
        public ContinueMailRequest() {
        }
        
        public ContinueMailRequest(eInventory.InternalMail.ContinueMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContinueMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TowhomSent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Conversation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strFilename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] data;
        
        public ContinueMailRequestBody() {
        }
        
        public ContinueMailRequestBody(string loginId, string TowhomSent, string Subject, string Conversation, string strFilename, byte[] data) {
            this.loginId = loginId;
            this.TowhomSent = TowhomSent;
            this.Subject = Subject;
            this.Conversation = Conversation;
            this.strFilename = strFilename;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContinueMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContinueMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public eInventory.InternalMail.ContinueMailResponseBody Body;
        
        public ContinueMailResponse() {
        }
        
        public ContinueMailResponse(eInventory.InternalMail.ContinueMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContinueMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ContinueMailResult;
        
        public ContinueMailResponseBody() {
        }
        
        public ContinueMailResponseBody(string ContinueMailResult) {
            this.ContinueMailResult = ContinueMailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InternalMail_WebServiceSoapChannel : eInventory.InternalMail.InternalMail_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalMail_WebServiceSoapClient : System.ServiceModel.ClientBase<eInventory.InternalMail.InternalMail_WebServiceSoap>, eInventory.InternalMail.InternalMail_WebServiceSoap {
        
        public InternalMail_WebServiceSoapClient() {
        }
        
        public InternalMail_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalMail_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalMail_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalMail_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eInventory.InternalMail.HelloWorldResponse eInventory.InternalMail.InternalMail_WebServiceSoap.HelloWorld(eInventory.InternalMail.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            eInventory.InternalMail.HelloWorldRequest inValue = new eInventory.InternalMail.HelloWorldRequest();
            inValue.Body = new eInventory.InternalMail.HelloWorldRequestBody();
            eInventory.InternalMail.HelloWorldResponse retVal = ((eInventory.InternalMail.InternalMail_WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eInventory.InternalMail.UploadFileToWebServerResponse eInventory.InternalMail.InternalMail_WebServiceSoap.UploadFileToWebServer(eInventory.InternalMail.UploadFileToWebServerRequest request) {
            return base.Channel.UploadFileToWebServer(request);
        }
        
        public string UploadFileToWebServer(string path, string filename, byte[] data) {
            eInventory.InternalMail.UploadFileToWebServerRequest inValue = new eInventory.InternalMail.UploadFileToWebServerRequest();
            inValue.Body = new eInventory.InternalMail.UploadFileToWebServerRequestBody();
            inValue.Body.path = path;
            inValue.Body.filename = filename;
            inValue.Body.data = data;
            eInventory.InternalMail.UploadFileToWebServerResponse retVal = ((eInventory.InternalMail.InternalMail_WebServiceSoap)(this)).UploadFileToWebServer(inValue);
            return retVal.Body.UploadFileToWebServerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eInventory.InternalMail.DownLoadFileFromWebServerResponse eInventory.InternalMail.InternalMail_WebServiceSoap.DownLoadFileFromWebServer(eInventory.InternalMail.DownLoadFileFromWebServerRequest request) {
            return base.Channel.DownLoadFileFromWebServer(request);
        }
        
        public byte[] DownLoadFileFromWebServer(string filename, string path) {
            eInventory.InternalMail.DownLoadFileFromWebServerRequest inValue = new eInventory.InternalMail.DownLoadFileFromWebServerRequest();
            inValue.Body = new eInventory.InternalMail.DownLoadFileFromWebServerRequestBody();
            inValue.Body.filename = filename;
            inValue.Body.path = path;
            eInventory.InternalMail.DownLoadFileFromWebServerResponse retVal = ((eInventory.InternalMail.InternalMail_WebServiceSoap)(this)).DownLoadFileFromWebServer(inValue);
            return retVal.Body.DownLoadFileFromWebServerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eInventory.InternalMail.NewMailResponse eInventory.InternalMail.InternalMail_WebServiceSoap.NewMail(eInventory.InternalMail.NewMailRequest request) {
            return base.Channel.NewMail(request);
        }
        
        public string NewMail(string loginId, string TowhomSent, string Subject, string Conversation, string strFilename, byte[] data) {
            eInventory.InternalMail.NewMailRequest inValue = new eInventory.InternalMail.NewMailRequest();
            inValue.Body = new eInventory.InternalMail.NewMailRequestBody();
            inValue.Body.loginId = loginId;
            inValue.Body.TowhomSent = TowhomSent;
            inValue.Body.Subject = Subject;
            inValue.Body.Conversation = Conversation;
            inValue.Body.strFilename = strFilename;
            inValue.Body.data = data;
            eInventory.InternalMail.NewMailResponse retVal = ((eInventory.InternalMail.InternalMail_WebServiceSoap)(this)).NewMail(inValue);
            return retVal.Body.NewMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eInventory.InternalMail.ContinueMailResponse eInventory.InternalMail.InternalMail_WebServiceSoap.ContinueMail(eInventory.InternalMail.ContinueMailRequest request) {
            return base.Channel.ContinueMail(request);
        }
        
        public string ContinueMail(string loginId, string TowhomSent, string Subject, string Conversation, string strFilename, byte[] data) {
            eInventory.InternalMail.ContinueMailRequest inValue = new eInventory.InternalMail.ContinueMailRequest();
            inValue.Body = new eInventory.InternalMail.ContinueMailRequestBody();
            inValue.Body.loginId = loginId;
            inValue.Body.TowhomSent = TowhomSent;
            inValue.Body.Subject = Subject;
            inValue.Body.Conversation = Conversation;
            inValue.Body.strFilename = strFilename;
            inValue.Body.data = data;
            eInventory.InternalMail.ContinueMailResponse retVal = ((eInventory.InternalMail.InternalMail_WebServiceSoap)(this)).ContinueMail(inValue);
            return retVal.Body.ContinueMailResult;
        }
    }
}
