//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eChandanCanteen.Inventory_WebServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Inventory_WebServices.Inventory_WebServicesSoap")]
    public interface Inventory_WebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillUnit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPurchIds(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVendorList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getVendorList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMfdAndPackOfItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getMfdAndPackOfItem(string item_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPurchases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddPurchases(string[] t1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ins_Purchase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ins_Purchase(
                    string Purch_id, 
                    string unit_id, 
                    string comp_code, 
                    string pur_type, 
                    string Vendor_Code, 
                    string Inv_No, 
                    string Inv_Date, 
                    string Item_id, 
                    string hsn, 
                    string mfd_id, 
                    string Batch_No, 
                    string Exp_Date, 
                    decimal MRP, 
                    decimal trade, 
                    string pack_type, 
                    decimal Quantity, 
                    decimal It_Free, 
                    decimal DisPer, 
                    int Tax_id, 
                    decimal BestRate, 
                    string Remark, 
                    string CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchasePosting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PurchasePosting(string[] p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchaseRecordByPurchId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPurchaseRecordByPurchId(string purch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Purchase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Delete_Purchase(string auto_id, string purch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTrfIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTrfIds(string trf_to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTrfRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTrfRecord(string transfer_id, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentTransferRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCurrentTransferRec(string transfer_id, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompleteTransfer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CompleteTransfer(string trf_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferStocks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TransferStocks(string[] t1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferStocks_Temp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TransferStocks_Temp(string[] t1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auto_DispatchProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Auto_DispatchProduct(string lot_no, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductIdentity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getProductIdentity(string item_id, string unit_id, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_TransferProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Delete_TransferProduct(string auto_id, string fromorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_TransferProduct_Temp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Delete_TransferProduct_Temp(string auto_id, string fromorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dispatch_Queries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Dispatch_Queries(out string processInfo, string unit_id, string lot_no, string trf_id, string prm_1, string prm_2, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_InterUnitTransferProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Delete_InterUnitTransferProduct(string auto_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProduct(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillMeasurementInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillMeasurementInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillPacks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillPacks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillManufacturer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillManufacturer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/feedCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string feedCategory(string cat_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUpdateProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateUpdateProduct(string hsn_code, string item_id, string item_name, string cat_id, string pack_size, int ROL, string dist_type, string mfd_id, string task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createPackSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string createPackSize(string packing, string qty, int pack_qty, string unit, string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillProductMdfyDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillProductMdfyDetail(string item_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillManufacturerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillManufacturerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAndModifyManufacturer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NewAndModifyManufacturer(string mfd_id, string mfd_name, string prmAddress, string prmPhone, string prmMobile, string email, string prmTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillManufacturerDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillManufacturerDetail(string mfd_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVendorDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getVendorDetail(string vend_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAndModifyVendor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NewAndModifyVendor(string vend_code, string vend_name, string address, string phone, string mobile_no, string tin_no, string state, string district, string task, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAndModifyCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NewAndModifyCustomer(string cust_id, string cust_type, string cust_name, string address, string phone, string mobile_no, string state, string district, string email, string linked_id, string task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillDistrict", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillDistrict(string state_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fillCustomerDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet fillCustomerDetail(string cust_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductSearchToSale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ProductSearchToSale(string item_name, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getProductDetail(string item_id, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createSale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string createSale(string inv_no, string master_key_id, string item_id, string unit_id, int qty, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSaledItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getSaledItems(string invoice_no, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetQueryResult(string query, string Database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryExecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryExecute(string query, string Database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stockAtUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet stockAtUnit(string unit_id, string comp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListofTransferedItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getListofTransferedItem(string unit_id, string trf_id, int receiptcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/receiveInStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string receiveInStock(string master_key, string trf_id, int qty, int rcpt_qty, string loginid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintTrfFormInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PrintTrfFormInfo(string trf_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrfIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TrfIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterUnitTransfer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InterUnitTransfer(string[] t1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/purchasReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string purchasReturn(string comp_code, string unitId, string masterkey, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoucherPosting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VoucherPosting(string unitId, string credit_ledger, string debit_ledger, decimal amount, string narration, string loginid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrfAndStockAndIssuedInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTrfAndStockAndIssuedInformation(string Item_id, string Unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IssueProduct(string master_key, int qty, string unit_id, string mfdId, string allotedto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIsuuedRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getIsuuedRecord(string unit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProductHistory(string unit_id, string item_id, string from_date, string to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBestRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateBestRate(string vend_code, string mfd_id, string item_id, string pack_size, decimal bestrate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateOrderInfo(string unit_id, string Item_id, string login_id, string pack_size, decimal pack_qty, decimal Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveErrorLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SaveErrorLog(string unitId, string errorLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarkByOrder_No", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MarkByOrder_No(string unit_id, int auto_id, string order_no, string login_id);
        
        // CODEGEN: Parameter 'doc' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsDocInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eChandanCanteen.Inventory_WebServices.InsDocInfoResponse InsDocInfo(eChandanCanteen.Inventory_WebServices.InsDocInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestPackSizeWithPendingOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLatestPackSizeWithPendingOrder(string unit_id, string item_id, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnProcessedOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUnProcessedOrder(out string processInfo, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderRawData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderRawData(out string processInfo, string unit_id, string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProductofUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProductofUnit(out string processInfo, string unit_id, string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrackUnitItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TrackUnitItem(out string processInfo, string item_id, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Audit_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="processInfo")]
        string Audit_Info(string userType, string workType, string login_id, string item_id, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIssuedRecToUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIssuedRecToUpdate(out string processInfo, string unit_id, string item_id, string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteIssuedItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="processInfo")]
        string DeleteIssuedItems(int auto_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GoodsReturnRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GoodsReturnRec(out string processInfo, string trf_id, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transfer_idCheckingInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Transfer_idCheckingInfo(out string processInfo, string unit_id, string trf_id, string from, string to, string logic);
        
        // CODEGEN: Parameter 'data' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_ScanedDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentResponse Insert_ScanedDocument(eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentRequest request);
        
        // CODEGEN: Parameter 'DownloadFileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eChandanCanteen.Inventory_WebServices.DownloadFileResponse DownloadFile(eChandanCanteen.Inventory_WebServices.DownloadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Quality_Querries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Quality_Querries(out string processInfo, string compl_id, string unit_id, string from, string to, string prm_1, string Logic);
        
        // CODEGEN: Parameter 'data' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuscribeComplaintDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailResponse SuscribeComplaintDetail(eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveStocksFromPharmacy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReceiveStocksFromPharmacy(out string processInfo, string unit_id, string trf_id, string logic, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GR_Processing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GR_Processing(out string processInfo, string trf_id, string master_key_id, string item_id, string unit_id, int qty, string vendor_code, decimal amount, string login_id, string logic, string gr_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReconcileProduct2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReconcileProduct2(out string processInfo, string unit_id, string logic, string prm_1, string prm_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Modify_Audit_master", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_Modify_Audit_master(string unit_id, string entry_type, string audit_no, string master_key_id, int qty, string login_id, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auto_DispatchForDamageOrExtra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Auto_DispatchForDamageOrExtra(string audit_no, string login_id, string trf_from, string trf_to, string logic);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsDocInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsDocInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string doc_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string doc_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string doc_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string remarks;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string login_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] doc;
        
        public InsDocInfoRequest() {
        }
        
        public InsDocInfoRequest(string doc_id, string doc_type, string subject, string doc_name, string remarks, string login_id, byte[] doc) {
            this.doc_id = doc_id;
            this.doc_type = doc_type;
            this.subject = subject;
            this.doc_name = doc_name;
            this.remarks = remarks;
            this.login_id = login_id;
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsDocInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsDocInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsDocInfoResult;
        
        public InsDocInfoResponse() {
        }
        
        public InsDocInfoResponse(string InsDocInfoResult) {
            this.InsDocInfoResult = InsDocInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_ScanedDocument", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_ScanedDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string login_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string unit_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        public Insert_ScanedDocumentRequest() {
        }
        
        public Insert_ScanedDocumentRequest(string DocId, string DocType, string login_id, string unit_id, byte[] data) {
            this.DocId = DocId;
            this.DocType = DocType;
            this.login_id = login_id;
            this.unit_id = unit_id;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_ScanedDocumentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_ScanedDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Insert_ScanedDocumentResult;
        
        public Insert_ScanedDocumentResponse() {
        }
        
        public Insert_ScanedDocumentResponse(string Insert_ScanedDocumentResult) {
            this.Insert_ScanedDocumentResult = Insert_ScanedDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Path;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(string Path) {
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string processInfo;
        
        public DownloadFileResponse() {
        }
        
        public DownloadFileResponse(byte[] DownloadFileResult, string processInfo) {
            this.DownloadFileResult = DownloadFileResult;
            this.processInfo = processInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SuscribeComplaintDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SuscribeComplaintDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compl_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string extension;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string remark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string login_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string result;
        
        public SuscribeComplaintDetailRequest() {
        }
        
        public SuscribeComplaintDetailRequest(string compl_id, string extension, string remark, byte[] data, string login_id, string result) {
            this.compl_id = compl_id;
            this.extension = extension;
            this.remark = remark;
            this.data = data;
            this.login_id = login_id;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SuscribeComplaintDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SuscribeComplaintDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SuscribeComplaintDetailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string processInfo;
        
        public SuscribeComplaintDetailResponse() {
        }
        
        public SuscribeComplaintDetailResponse(string SuscribeComplaintDetailResult, string processInfo) {
            this.SuscribeComplaintDetailResult = SuscribeComplaintDetailResult;
            this.processInfo = processInfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Inventory_WebServicesSoapChannel : eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Inventory_WebServicesSoapClient : System.ServiceModel.ClientBase<eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap>, eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap {
        
        public Inventory_WebServicesSoapClient() {
        }
        
        public Inventory_WebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Inventory_WebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Inventory_WebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Inventory_WebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet fillUnit() {
            return base.Channel.fillUnit();
        }
        
        public System.Data.DataSet getPurchIds(int num) {
            return base.Channel.getPurchIds(num);
        }
        
        public System.Data.DataSet getVendorList() {
            return base.Channel.getVendorList();
        }
        
        public System.Data.DataSet getMfdAndPackOfItem(string item_id) {
            return base.Channel.getMfdAndPackOfItem(item_id);
        }
        
        public string AddPurchases(string[] t1) {
            return base.Channel.AddPurchases(t1);
        }
        
        public string Ins_Purchase(
                    string Purch_id, 
                    string unit_id, 
                    string comp_code, 
                    string pur_type, 
                    string Vendor_Code, 
                    string Inv_No, 
                    string Inv_Date, 
                    string Item_id, 
                    string hsn, 
                    string mfd_id, 
                    string Batch_No, 
                    string Exp_Date, 
                    decimal MRP, 
                    decimal trade, 
                    string pack_type, 
                    decimal Quantity, 
                    decimal It_Free, 
                    decimal DisPer, 
                    int Tax_id, 
                    decimal BestRate, 
                    string Remark, 
                    string CreatedBy) {
            return base.Channel.Ins_Purchase(Purch_id, unit_id, comp_code, pur_type, Vendor_Code, Inv_No, Inv_Date, Item_id, hsn, mfd_id, Batch_No, Exp_Date, MRP, trade, pack_type, Quantity, It_Free, DisPer, Tax_id, BestRate, Remark, CreatedBy);
        }
        
        public string PurchasePosting(string[] p) {
            return base.Channel.PurchasePosting(p);
        }
        
        public System.Data.DataSet getPurchaseRecordByPurchId(string purch_id) {
            return base.Channel.getPurchaseRecordByPurchId(purch_id);
        }
        
        public string Delete_Purchase(string auto_id, string purch_id) {
            return base.Channel.Delete_Purchase(auto_id, purch_id);
        }
        
        public System.Data.DataSet getTrfIds(string trf_to) {
            return base.Channel.getTrfIds(trf_to);
        }
        
        public System.Data.DataSet getTrfRecord(string transfer_id, string unit_id) {
            return base.Channel.getTrfRecord(transfer_id, unit_id);
        }
        
        public System.Data.DataSet GetCurrentTransferRec(string transfer_id, string unit_id) {
            return base.Channel.GetCurrentTransferRec(transfer_id, unit_id);
        }
        
        public string CompleteTransfer(string trf_id) {
            return base.Channel.CompleteTransfer(trf_id);
        }
        
        public string TransferStocks(string[] t1) {
            return base.Channel.TransferStocks(t1);
        }
        
        public string TransferStocks_Temp(string[] t1) {
            return base.Channel.TransferStocks_Temp(t1);
        }
        
        public string Auto_DispatchProduct(string lot_no, string login_id) {
            return base.Channel.Auto_DispatchProduct(lot_no, login_id);
        }
        
        public System.Data.DataSet getProductIdentity(string item_id, string unit_id, string comp_code) {
            return base.Channel.getProductIdentity(item_id, unit_id, comp_code);
        }
        
        public string Delete_TransferProduct(string auto_id, string fromorder) {
            return base.Channel.Delete_TransferProduct(auto_id, fromorder);
        }
        
        public string Delete_TransferProduct_Temp(string auto_id, string fromorder) {
            return base.Channel.Delete_TransferProduct_Temp(auto_id, fromorder);
        }
        
        public System.Data.DataSet Dispatch_Queries(out string processInfo, string unit_id, string lot_no, string trf_id, string prm_1, string prm_2, string Logic) {
            return base.Channel.Dispatch_Queries(out processInfo, unit_id, lot_no, trf_id, prm_1, prm_2, Logic);
        }
        
        public string Delete_InterUnitTransferProduct(string auto_id) {
            return base.Channel.Delete_InterUnitTransferProduct(auto_id);
        }
        
        public System.Data.DataSet SearchProduct(string key) {
            return base.Channel.SearchProduct(key);
        }
        
        public System.Data.DataSet fillMeasurementInfo() {
            return base.Channel.fillMeasurementInfo();
        }
        
        public System.Data.DataSet fillCategory() {
            return base.Channel.fillCategory();
        }
        
        public System.Data.DataSet fillPacks() {
            return base.Channel.fillPacks();
        }
        
        public System.Data.DataSet fillManufacturer() {
            return base.Channel.fillManufacturer();
        }
        
        public string feedCategory(string cat_name) {
            return base.Channel.feedCategory(cat_name);
        }
        
        public string CreateUpdateProduct(string hsn_code, string item_id, string item_name, string cat_id, string pack_size, int ROL, string dist_type, string mfd_id, string task) {
            return base.Channel.CreateUpdateProduct(hsn_code, item_id, item_name, cat_id, pack_size, ROL, dist_type, mfd_id, task);
        }
        
        public string createPackSize(string packing, string qty, int pack_qty, string unit, string Description) {
            return base.Channel.createPackSize(packing, qty, pack_qty, unit, Description);
        }
        
        public System.Data.DataSet fillProduct() {
            return base.Channel.fillProduct();
        }
        
        public System.Data.DataSet fillProductMdfyDetail(string item_id) {
            return base.Channel.fillProductMdfyDetail(item_id);
        }
        
        public System.Data.DataSet fillManufacturerList() {
            return base.Channel.fillManufacturerList();
        }
        
        public string NewAndModifyManufacturer(string mfd_id, string mfd_name, string prmAddress, string prmPhone, string prmMobile, string email, string prmTask) {
            return base.Channel.NewAndModifyManufacturer(mfd_id, mfd_name, prmAddress, prmPhone, prmMobile, email, prmTask);
        }
        
        public System.Data.DataSet fillManufacturerDetail(string mfd_id) {
            return base.Channel.fillManufacturerDetail(mfd_id);
        }
        
        public System.Data.DataSet getVendorDetail(string vend_code) {
            return base.Channel.getVendorDetail(vend_code);
        }
        
        public string NewAndModifyVendor(string vend_code, string vend_name, string address, string phone, string mobile_no, string tin_no, string state, string district, string task, string remark) {
            return base.Channel.NewAndModifyVendor(vend_code, vend_name, address, phone, mobile_no, tin_no, state, district, task, remark);
        }
        
        public string NewAndModifyCustomer(string cust_id, string cust_type, string cust_name, string address, string phone, string mobile_no, string state, string district, string email, string linked_id, string task) {
            return base.Channel.NewAndModifyCustomer(cust_id, cust_type, cust_name, address, phone, mobile_no, state, district, email, linked_id, task);
        }
        
        public System.Data.DataSet fillState() {
            return base.Channel.fillState();
        }
        
        public System.Data.DataSet fillDistrict(string state_code) {
            return base.Channel.fillDistrict(state_code);
        }
        
        public System.Data.DataSet fillCustomer() {
            return base.Channel.fillCustomer();
        }
        
        public System.Data.DataSet fillCustomerDetail(string cust_id) {
            return base.Channel.fillCustomerDetail(cust_id);
        }
        
        public System.Data.DataSet ProductSearchToSale(string item_name, string unit_id) {
            return base.Channel.ProductSearchToSale(item_name, unit_id);
        }
        
        public System.Data.DataSet getProductDetail(string item_id, string unit_id) {
            return base.Channel.getProductDetail(item_id, unit_id);
        }
        
        public string createSale(string inv_no, string master_key_id, string item_id, string unit_id, int qty, string login_id) {
            return base.Channel.createSale(inv_no, master_key_id, item_id, unit_id, qty, login_id);
        }
        
        public System.Data.DataSet getSaledItems(string invoice_no, string unit_id) {
            return base.Channel.getSaledItems(invoice_no, unit_id);
        }
        
        public System.Data.DataSet GetQueryResult(string query, string Database) {
            return base.Channel.GetQueryResult(query, Database);
        }
        
        public string QueryExecute(string query, string Database) {
            return base.Channel.QueryExecute(query, Database);
        }
        
        public System.Data.DataSet stockAtUnit(string unit_id, string comp_code) {
            return base.Channel.stockAtUnit(unit_id, comp_code);
        }
        
        public System.Data.DataSet getListofTransferedItem(string unit_id, string trf_id, int receiptcode) {
            return base.Channel.getListofTransferedItem(unit_id, trf_id, receiptcode);
        }
        
        public string receiveInStock(string master_key, string trf_id, int qty, int rcpt_qty, string loginid) {
            return base.Channel.receiveInStock(master_key, trf_id, qty, rcpt_qty, loginid);
        }
        
        public System.Data.DataSet PrintTrfFormInfo(string trf_id) {
            return base.Channel.PrintTrfFormInfo(trf_id);
        }
        
        public System.Data.DataSet TrfIds() {
            return base.Channel.TrfIds();
        }
        
        public string InterUnitTransfer(string[] t1) {
            return base.Channel.InterUnitTransfer(t1);
        }
        
        public string purchasReturn(string comp_code, string unitId, string masterkey, int qty) {
            return base.Channel.purchasReturn(comp_code, unitId, masterkey, qty);
        }
        
        public string VoucherPosting(string unitId, string credit_ledger, string debit_ledger, decimal amount, string narration, string loginid) {
            return base.Channel.VoucherPosting(unitId, credit_ledger, debit_ledger, amount, narration, loginid);
        }
        
        public System.Data.DataSet GetTrfAndStockAndIssuedInformation(string Item_id, string Unit_id) {
            return base.Channel.GetTrfAndStockAndIssuedInformation(Item_id, Unit_id);
        }
        
        public System.Data.DataSet IssueProduct(string master_key, int qty, string unit_id, string mfdId, string allotedto) {
            return base.Channel.IssueProduct(master_key, qty, unit_id, mfdId, allotedto);
        }
        
        public System.Data.DataSet getIsuuedRecord(string unit) {
            return base.Channel.getIsuuedRecord(unit);
        }
        
        public System.Data.DataSet GetProductHistory(string unit_id, string item_id, string from_date, string to_date) {
            return base.Channel.GetProductHistory(unit_id, item_id, from_date, to_date);
        }
        
        public string CreateBestRate(string vend_code, string mfd_id, string item_id, string pack_size, decimal bestrate) {
            return base.Channel.CreateBestRate(vend_code, mfd_id, item_id, pack_size, bestrate);
        }
        
        public string CreateOrderInfo(string unit_id, string Item_id, string login_id, string pack_size, decimal pack_qty, decimal Qty) {
            return base.Channel.CreateOrderInfo(unit_id, Item_id, login_id, pack_size, pack_qty, Qty);
        }
        
        public void SaveErrorLog(string unitId, string errorLog) {
            base.Channel.SaveErrorLog(unitId, errorLog);
        }
        
        public string MarkByOrder_No(string unit_id, int auto_id, string order_no, string login_id) {
            return base.Channel.MarkByOrder_No(unit_id, auto_id, order_no, login_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eChandanCanteen.Inventory_WebServices.InsDocInfoResponse eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap.InsDocInfo(eChandanCanteen.Inventory_WebServices.InsDocInfoRequest request) {
            return base.Channel.InsDocInfo(request);
        }
        
        public string InsDocInfo(string doc_id, string doc_type, string subject, string doc_name, string remarks, string login_id, byte[] doc) {
            eChandanCanteen.Inventory_WebServices.InsDocInfoRequest inValue = new eChandanCanteen.Inventory_WebServices.InsDocInfoRequest();
            inValue.doc_id = doc_id;
            inValue.doc_type = doc_type;
            inValue.subject = subject;
            inValue.doc_name = doc_name;
            inValue.remarks = remarks;
            inValue.login_id = login_id;
            inValue.doc = doc;
            eChandanCanteen.Inventory_WebServices.InsDocInfoResponse retVal = ((eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap)(this)).InsDocInfo(inValue);
            return retVal.InsDocInfoResult;
        }
        
        public System.Data.DataSet GetLatestPackSizeWithPendingOrder(string unit_id, string item_id, string login_id) {
            return base.Channel.GetLatestPackSizeWithPendingOrder(unit_id, item_id, login_id);
        }
        
        public System.Data.DataSet GetUnProcessedOrder(out string processInfo, string unit_id) {
            return base.Channel.GetUnProcessedOrder(out processInfo, unit_id);
        }
        
        public System.Data.DataSet GetOrderRawData(out string processInfo, string unit_id, string from, string to) {
            return base.Channel.GetOrderRawData(out processInfo, unit_id, from, to);
        }
        
        public System.Data.DataSet SearchProductofUnit(out string processInfo, string unit_id, string searchString) {
            return base.Channel.SearchProductofUnit(out processInfo, unit_id, searchString);
        }
        
        public System.Data.DataSet TrackUnitItem(out string processInfo, string item_id, string unit_id) {
            return base.Channel.TrackUnitItem(out processInfo, item_id, unit_id);
        }
        
        public string Audit_Info(string userType, string workType, string login_id, string item_id, string remark) {
            return base.Channel.Audit_Info(userType, workType, login_id, item_id, remark);
        }
        
        public System.Data.DataSet GetIssuedRecToUpdate(out string processInfo, string unit_id, string item_id, string from, string to) {
            return base.Channel.GetIssuedRecToUpdate(out processInfo, unit_id, item_id, from, to);
        }
        
        public string DeleteIssuedItems(int auto_id) {
            return base.Channel.DeleteIssuedItems(auto_id);
        }
        
        public System.Data.DataSet GoodsReturnRec(out string processInfo, string trf_id, string unit_id) {
            return base.Channel.GoodsReturnRec(out processInfo, trf_id, unit_id);
        }
        
        public System.Data.DataSet Transfer_idCheckingInfo(out string processInfo, string unit_id, string trf_id, string from, string to, string logic) {
            return base.Channel.Transfer_idCheckingInfo(out processInfo, unit_id, trf_id, from, to, logic);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentResponse eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap.Insert_ScanedDocument(eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentRequest request) {
            return base.Channel.Insert_ScanedDocument(request);
        }
        
        public string Insert_ScanedDocument(string DocId, string DocType, string login_id, string unit_id, byte[] data) {
            eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentRequest inValue = new eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentRequest();
            inValue.DocId = DocId;
            inValue.DocType = DocType;
            inValue.login_id = login_id;
            inValue.unit_id = unit_id;
            inValue.data = data;
            eChandanCanteen.Inventory_WebServices.Insert_ScanedDocumentResponse retVal = ((eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap)(this)).Insert_ScanedDocument(inValue);
            return retVal.Insert_ScanedDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eChandanCanteen.Inventory_WebServices.DownloadFileResponse eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap.DownloadFile(eChandanCanteen.Inventory_WebServices.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public byte[] DownloadFile(string Path, out string processInfo) {
            eChandanCanteen.Inventory_WebServices.DownloadFileRequest inValue = new eChandanCanteen.Inventory_WebServices.DownloadFileRequest();
            inValue.Path = Path;
            eChandanCanteen.Inventory_WebServices.DownloadFileResponse retVal = ((eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap)(this)).DownloadFile(inValue);
            processInfo = retVal.processInfo;
            return retVal.DownloadFileResult;
        }
        
        public System.Data.DataSet Quality_Querries(out string processInfo, string compl_id, string unit_id, string from, string to, string prm_1, string Logic) {
            return base.Channel.Quality_Querries(out processInfo, compl_id, unit_id, from, to, prm_1, Logic);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailResponse eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap.SuscribeComplaintDetail(eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailRequest request) {
            return base.Channel.SuscribeComplaintDetail(request);
        }
        
        public string SuscribeComplaintDetail(string compl_id, string extension, string remark, byte[] data, string login_id, string result, out string processInfo) {
            eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailRequest inValue = new eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailRequest();
            inValue.compl_id = compl_id;
            inValue.extension = extension;
            inValue.remark = remark;
            inValue.data = data;
            inValue.login_id = login_id;
            inValue.result = result;
            eChandanCanteen.Inventory_WebServices.SuscribeComplaintDetailResponse retVal = ((eChandanCanteen.Inventory_WebServices.Inventory_WebServicesSoap)(this)).SuscribeComplaintDetail(inValue);
            processInfo = retVal.processInfo;
            return retVal.SuscribeComplaintDetailResult;
        }
        
        public System.Data.DataSet ReceiveStocksFromPharmacy(out string processInfo, string unit_id, string trf_id, string logic, string login_id) {
            return base.Channel.ReceiveStocksFromPharmacy(out processInfo, unit_id, trf_id, logic, login_id);
        }
        
        public string GR_Processing(out string processInfo, string trf_id, string master_key_id, string item_id, string unit_id, int qty, string vendor_code, decimal amount, string login_id, string logic, string gr_no) {
            return base.Channel.GR_Processing(out processInfo, trf_id, master_key_id, item_id, unit_id, qty, vendor_code, amount, login_id, logic, gr_no);
        }
        
        public System.Data.DataSet ReconcileProduct2(out string processInfo, string unit_id, string logic, string prm_1, string prm_2) {
            return base.Channel.ReconcileProduct2(out processInfo, unit_id, logic, prm_1, prm_2);
        }
        
        public string Insert_Modify_Audit_master(string unit_id, string entry_type, string audit_no, string master_key_id, int qty, string login_id, string Logic) {
            return base.Channel.Insert_Modify_Audit_master(unit_id, entry_type, audit_no, master_key_id, qty, login_id, Logic);
        }
        
        public string Auto_DispatchForDamageOrExtra(string audit_no, string login_id, string trf_from, string trf_to, string logic) {
            return base.Channel.Auto_DispatchForDamageOrExtra(audit_no, login_id, trf_from, trf_to, logic);
        }
    }
}
